ktor:
    application:
        modules:
            - com.factsmachine.ApplicationKt.module
    deployment:
        port: 8080
    uselessfactsservice:
        url: "https://uselessfacts.jsph.pl/api/v2/facts/random"
    baseurl: "http://localhost:8080/facts/"
